{% set name = "scanf" %}
{% set version = "1.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7671292b825eb1cbdbdcacf3e30e761fc482bf3671c835e216b8b6f14758a272
  patches:
    - python.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - flit-core
  run:
    - python >={{ python_min }}

test:
  imports:
    - scanf
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/joshburnett/scanf
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A small scanf implementation

  description: |
    Python has powerful regular expressions but they can be totally 
    overkill for many simpler situations. Additionally, some common 
    numerical formats require quite complex regex's to match them 
    robustly. This python implementation of scanf internally 
    translates the simple scanf format into regular expressions, 
    then returns the parsed values.
  doc_url: https://github.com/joshburnett/scanf
  dev_url: https://github.com/joshburnett/scanf

extra:
  recipe-maintainers:
    - jan-janssen
